Allow dvd_source to be a directory or device node.

diff --git a/pawl b/pawl
--- a/pawl
+++ b/pawl
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: pawl,v 1.43 2010/08/17 01:16:22 bus Exp bus $
+# $Id: pawl,v 1.44 2010/08/17 03:10:58 bus Exp bus $
 #
 
 set -e
@@ -20,7 +20,7 @@ fi
 pawl_config_version='13'
 
 # Defaults
-dvd_source=''
+dvd_source='/dev/dvd'
 output=''
 audio_tracks='1'
 audio_encoder='ac3'
@@ -77,7 +77,7 @@ if [ "$1" = "config" ]; then
 		echo ' !!!'
 	fi
 	cat <<_EOF_ > config
-# Source footage.  Needs to be a directory, not a DVD device.
+# Source footage.  May be a directory or DVD device node.  Default: /dev/dvd
 dvd_source='$dvd_source'
 
 # Output filename.  Do not include a filename extension.
@@ -257,6 +257,7 @@ bframes=5"
 output_format='mkv'
 
 # Re-set some mandatory defaults if the config file blanked them out.
+test -z "$dvd_source" && dvd_source='/dev/dvd'
 test -z "$title" && title='1'
 test -z "$audio_tracks" && audio_tracks='1'
 test -z "$audio_encoder" && audio_encoder='ac3'
@@ -308,9 +309,18 @@ fi
 
 # compare?
 if [ "$1" = 'compare' ]; then
-	if [ ! -d "$dvd_source" ]; then
+	dvd_source_dir="$dvd_source"
+	if [ -b "$dvd_source" ]; then
+		dvd_device=`realpath "$dvd_source"`
+		if ! mount | grep "^${dvd_device} on " >/dev/null 2>&1; then
+			set +x
+			echo 'DVD not present in drive.  Aborting.' 1>&2
+			exit 1
+		fi
+		dvd_source_dir=`mount | grep "^${dvd_device} on " | awk '{print $3}'`
+	elif [ ! -d "$dvd_source" ]; then
 		set +x
-		echo 'DVD source directory not present.  Aborting.' 1>&2
+		echo 'DVD source not present.  Aborting.' 1>&2
 		exit 1
 	fi
 	if [ ! -f "${output}.${output_format}" ]; then
@@ -319,7 +329,7 @@ if [ "$1" = 'compare' ]; then
 		exit 1
 	fi
 	set +x
-	du -sh "$dvd_source" "${output}.${output_format}"
+	du -sh "$dvd_source_dir" "${output}.${output_format}"
 	exit
 fi
 
