Add playsrc and playout feature.
- Add features to use mplayer to play the source and the output.

- Abstract has_* and require_* functions so they can be used to detect
  any arbitrary command. Use these to detect mplayer, transcode, and
  tcprobe.

diff --git a/pawl b/pawl
--- a/pawl
+++ b/pawl
@@ -128,28 +128,19 @@ else
 	exit 1
 fi
 
-has_tcprobe () {
+has_cmd () {
 	local rc
 	set +e
-	"$which_cmd" tcprobe 2>&1 >/dev/null
+	"$which_cmd" "$1" 2>&1 >/dev/null
 	rc=$?
 	set -e
 	return $rc
 }
 
-has_transcode () {
-	local rc
-	set +e
-	"$which_cmd" transcode 2>&1 >/dev/null
-	rc=$?
-	set -e
-	return $rc
-}
-
-require_transcode () {
-	if ! has_transcode; then
+require_cmd () {
+	if ! has_cmd "$1" ; then
 		set +x
-		echo "ERROR: transcode is required for this function." 1>&2
+		echo "ERROR: $1 is required for this function." 1>&2
 		exit 1
 	fi
 	return 0
@@ -192,6 +183,8 @@ usage () {
 	echo '       32detect     (check source for sporadic interlaced frames)'
 	echo '       compare      (compare size of DVD source vs. project output)'
 	echo '       extractframe (extract one or more frames.  arg: f1,f2,f3-f4[,f4-f5])'
+	echo '       playsrc      (Play source)'
+	echo '       playout      (Play output)'
 	exit $rc
 }
 
@@ -207,7 +200,9 @@ test "$1" = 'config'       -o \
      "$1" = 'scan'         -o \
      "$1" = '32detect'     -o \
      "$1" = 'compare'      -o \
-     "$1" = 'extractframe' || usage 1
+     "$1" = 'extractframe' -o \
+     "$1" = 'playsrc'      -o \
+     "$1" = 'playout'      || usage 1
 
 # Scaffold
 if [ "$1" = "config" ]; then
@@ -482,13 +477,13 @@ fi
 # Scan mode?
 if [ "$1" = 'scan' ]; then
 	HandBrakeCLI -i "$dvd_source" -t 0 -v > handbrake-scan.log 2>&1
-	if has_tcprobe; then
+	if has_cmd tcprobe; then
 		tcprobe -i "$dvd_source" \
 		        -H 10 -T "$title" > tcprobe-scan.log 2>&1
 	fi
 	set +x
 	echo 'HandBrakeCLI scan is in handbrake-scan.log'
-	if has_tcprobe; then
+	if has_cmd tcprobe; then
 		echo 'tcprobe scan is in tcprobe-scan.log'
 	fi
 	exit
@@ -496,7 +491,7 @@ fi
 
 # 32detect?
 if [ "$1" = '32detect' ]; then
-	require_transcode
+	require_cmd transcode
 	transcode -J 32detect=force_mode=0:verbose -M 0 -x dvd \
 	          -i "$dvd_source" $tc_title_chapters_arg --progress_off \
 	          -H 10 2>&1 | grep 'interlaced = yes' | \
@@ -543,7 +538,7 @@ if [ "$1" = 'extractframe' ]; then
 		exit 1
 	fi
 
-	require_transcode
+	require_cmd transcode
 
 	# Now it gets a little tricky.  transcode's frame selection options
 	# aren't inclusive,  That is -c 97769 won't give you a single frame,
@@ -576,6 +571,20 @@ if [ "$1" = 'extractframe' ]; then
 	          -i "$dvd_source" $tc_title_chapters_arg \
 	          -H 10 -c $p -y jpg,null -o frame
 	exit
+fi
+
+# play source?
+if [ "$1" = 'playsrc' ]; then
+	require_cmd mplayer
+	mplayer -dvd-device "$dvd_source" dvd://"${title}"
+	exit $?
+fi
+
+# play output?
+if [ "$1" = 'playout' ]; then
+	require_cmd mplayer
+	mplayer "${output}.${output_format}"
+	exit $?
 fi
 
 # Assertion: If we're this far, we're running a project. Make sure the user
@@ -655,7 +664,7 @@ esac
 
 # Create chapters.csv if needed.
 if [ "$chapter_markers" = 'Yes' -a ! -f 'chapters.csv' ]; then
-	if has_tcprobe; then
+	if has_cmd tcprobe; then
 		_number_of_chapters=`tcprobe -i "$dvd_source" -H 10 -T "$title" 2>&1 | grep ' DVD title ' | $esed_cmd 's,.*: ([0-9]+) chapter.*,\1,'`
 		c=1
 		while [ $c -le $_number_of_chapters ]; do
